spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://mongouser:mangopassword@testdb.wgarjwv.mongodb.net/?retryWrites=true&w=majority
#      database: testdb
  data:
    mongodb:
      primary:
        uri: mongodb+srv://mongouser:mangopassword@testdb.wgarjwv.mongodb.net/?retryWrites=true&w=majority
        database: testdb
      secondary:
        uri: mongodb+srv://mongouser:mangopassword@testdb2.wgarjwv.mongodb.net/?retryWrites=true&w=majority
        database: testdb2
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: embedded
server:
  port: 8085

mongo:
  primary:
    uri: mongodb+srv://mongouser:mangopassword@testdb.wgarjwv.mongodb.net/?retryWrites=true&w=majority
    database: testdb
  secondary:
    uri: mongodb+srv://mongouser:mangopassword@testdb2.wgarjwv.mongodb.net/?retryWrites=true&w=majority
    database: testdb2